### Social Network Graph
The first part of this project is modeling the social network over which we will simulate different events, namely parties, decay of relationships, falling outs, and meeting people.

We determined that the components of the graph are
* People: Each person is represented by a node
* Frendship / connection: Two connected people have an edge between them. The frequency of there being a connected is modeled off of Dunbar's number [(source)](https://www.bbc.com/future/article/20191001-dunbars-number-why-we-can-only-maintain-150-relationships).
* Friendship level: The friendship level of these two people are represented as the weight of the edge. The specific friendship level is chosen using Dunbar's number [(source)](https://www.bbc.com/future/article/20191001-dunbars-number-why-we-can-only-maintain-150-relationships). The specific break downs are:
    * Enemies (??): -1 
    * People you can recognize (1500): $\frac{0}{2215} \le x < \frac{1500}{2215}$.For most of our calculations, we will considert this range essentially 0.
    * Acquaintances (500): $\frac{1500}{2215} \le x < \frac{2000}{2215}$
    * Meaningful contacts (150): $\frac{2000}{2215} \le x < \frac{2150}{2215}$
    * Friends (50): $\frac{2150}{2215} \le x < \frac{2200}{2215}$
    * Good Friends (15): $\frac{2200}{2215} \le x < \frac{2215}{2215}$

In [1]:
import numpy as np
import math
from itertools import permutations

In [3]:
def generate_graph(n: int, p:float):
    # generate the graph parameters
    connections = np.random.uniform(low=0, high=1, size=((n+1)*(n)//2)) > p
    weights = np.random.uniform(low=0, high=1, size=((n+1)*(n)//2))

    # fill out actual graph
    graph = np.zeros((n, n))
    ui = (np.triu_indices(n)) # indices of the upper triangular matrix
    graph[ui] = weights
    graph[ui] = graph[ui] * connections# np.ma.masked_array(graph[ui], mask=connections) 

    # transpose edges for undirected graph
    graph = graph + np.transpose(graph[:, :])

    x = np.arange(n)

    graph[x, x] = 0 
    
    return graph

In [4]:
graph = generate_graph(4000, 1-2215/4000)
graph

array([[0.        , 0.        , 0.        , ..., 0.2095336 , 0.90327021,
        0.23087665],
       [0.        , 0.        , 0.        , ..., 0.79410067, 0.02675825,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.55934046, 0.10162063,
        0.        ],
       ...,
       [0.2095336 , 0.79410067, 0.55934046, ..., 0.        , 0.        ,
        0.30761531],
       [0.90327021, 0.02675825, 0.10162063, ..., 0.        , 0.        ,
        0.63673394],
       [0.23087665, 0.        , 0.        , ..., 0.30761531, 0.63673394,
        0.        ]])

In [5]:
# This function generates the social connections (direct and indirect) between some given person and all other people. In the instance where this person and another person
# are directly connected, the 'social connection' value will likely be equivalent to their current friendship level. Otherwise, indirect connects can have a social connection
# with the given person if they are typically w/in one degree, with a high level of friendship to the intermediary (some friends, and good friends. Occurs about 1% of the time)
# AND the intermediary has a high degree of friendship to the original person. A friend of a friend, so to speak.

def generate_social_connections(graph, person):
    # Build the initial social connections based off the person's direct network
    connectedness = graph[person].copy()
    
    # Note the blacklisted people
    black_list = np.where(connectedness < 0)[0]

    # Create a filter that removes blacklisted people
    mask = np.zeros(connectedness.size, dtype=bool)
    mask[black_list] = True
    mask[person] = True
    mask = np.vstack((mask, mask))
    

    # Apply the filter to connectedness, giving possible guests
    possible = np.ma.array(np.vstack((connectedness, np.array([1]*connectedness.shape[0]))), mask=mask)

        #print("step 1", possible) #testing
    
    # Continue below operations until the social connection value is arbitrarily low (within the lowest catgory)
    while (possible[0] >= 1500/2215).sum() > 0:

            #print("entered loop!") #testing
        
        # Choose the next highest social connection
        next_guest = np.argmax(possible[0])
        guest_distance = possible[1, next_guest]
        connectedness[next_guest] = possible[0, next_guest]

            #print("next guest:", next_guest, "distance:", guest_distance) #testing

        # Update filter to include the next added guest since we do not want to update this value.
        mask[:, next_guest] = True
        possible = np.ma.array(possible, mask=mask)
            #print("masked off next guest", possible) #testing

        
        # Improve social connections if a person is indirectly connected to the person
        updater = possible[0] < connectedness[next_guest] * graph[next_guest] / (guest_distance + 1)**(1/1.83)
            #print("updater", updater) # testing
        possible[1, updater] = guest_distance + 1
        possible[0, updater] = (connectedness[next_guest] * graph[next_guest] / (possible[1])**(1/1.83))[updater]

            #print("updated possible", possible) #testing
    
    return connectedness

In [25]:
def determine_host(graph):
    # Get the number of people in the graph
    num_people = graph.shape[0]
    # Randomly select a host from the range of people
    host = np.random.randint(0, num_people)
    return host

def determine_invited(graph, host, threshold, blacklist):
    # Get the friendship levels of the host
    friendship_levels = graph[host]
    # Create a mask for invited guests based on the threshold and blacklist
    invited_mask = (friendship_levels > threshold) & (~np.isin(np.arange(graph.shape[0]), blacklist))
    # Get the list of invited guests
    invited_guests = np.where(invited_mask)[0]
    return invited_guests

In [ ]:
test_graph = generate_graph(4000, 1-2215/4000)
connections = generate_social_connections(test_graph, 4)


print("Direct social connections vs. Total Social Connections")
print("Total edge weight:",sum(test_graph[4]), sum(connections))
print("Number of important edges(non-arbitrary connection):", sum(test_graph[4] > 1500/2215), sum(connections > 1500/2215))
print("Total number of edges:", sum(test_graph[4] > 0), sum(connections > 0))

print("\nGranular breakdown of direct and total social connections")
print("Number of acquaintances+:", sum((test_graph[4]) > 1500/2215),sum(connections > 1500/2215))
print("Number of meaningful contacts+:", sum(test_graph[4] > 2000/2215),sum(connections > 2000/2215))
print("Number of friends+:", sum(test_graph[4]>2150/2215), sum(connections > 2150/2215))
print("Number of good friends+:", sum(test_graph[4]>2200/2215),sum(connections > 2200/2215))


host = determine_host(graph)
black_list = np.where(test_graph[4].copy() < 0)[0]
threshold_input = input("Enter the friendship level threshold for invitations (eg 2100/2215): ")
threshold = eval(threshold_input)  # Evaluate the input to calculate the threshold

invited_guests = determine_invited(graph, host, threshold, black_list)

print(f"Random Host: {host}, Invited Guests: {invited_guests}")

Direct social connections vs. Total Social Connections
Total edge weight: 1120.714655214607 1228.1266247903882
Number of important edges(non-arbitrary connection): 740 947
Total number of edges: 2223 2336

Granular breakdown of direct and total social connections
Number of acquaintances+: 740 947
Number of meaningful contacts+: 228 228
Number of friends+: 67 67
Number of good friends+: 12 12


In [7]:
(1- ((1500/2215) * (2)**(1/1.83))) #Rough percentage of occurence

0.010957864640372073

### Decaying Friendships and Enemies

In [8]:
# This function will occur after a party happens
# Friendships will decay generally if two people were not in the same party together
# A select few random friendships will become enemies

def friendship_decay(graph, party: list[int]):
    # Get every pairing of people at the party
    party_pairs = list(permutations(party, 2))
    x, y = zip(*party_pairs)

    # Take note of the current values of the people who went to the party together
    sustained = graph[list(x), list(y)].copy()

    # Decrease friendship levels
    graph[(graph < 1500 /2215) & (graph > 0)] *= 0.60 # May need to play with these rates more to make it correct.
    graph[(graph < 2000 / 2215) & (graph >= 1500/2215)] *= 0.8
    graph[(graph < 2150 / 2215) & (graph >= 2000/2215)] *= 0.95
    graph[(graph < 2200 / 2215) & (graph >= 2150/2215)] *= 0.99
    graph[(graph <= 1) & (graph >= 2200/2215)] *= 0.997

    # Decrease enemy levels
    graph[(graph >= -1) & (graph < -2200/2215)] *= 0.997
    graph[(graph >= -2200/2215) & (graph < -2150/2215)] *= 0.99
    graph[(graph >= -2150 / 2215) & (graph < -2000/2215)] *= 0.95
    graph[(graph >= -2000/2215) & (graph < -1500/2215)] *= 0.8
    graph[(graph >= -1500 /2215) & (graph < 0)] *= 0.60

    # If the value is under 0.1, set to 0.
    graph[(abs(graph) < 0.1)] = 0

    # Reinstate the social connections level for people at the party
    graph[list(x), list(y)] = sustained

    return graph

def sudden_enemies(graph, num):
    n = graph.shape[0]
    i = 0
    while i < num:
        nodes = np.random.randint(0, high=n, size=(2))

        if nodes[0] == nodes[1]:
            i = i-1
        else:
            graph[nodes[0], nodes[1]] = -1
            graph[nodes[1], nodes[0]] = -1
        i += 1
    return graph

In [9]:
tester = generate_graph(4, 1-2215/4000)
tester = sudden_enemies(tester, 2)

tester

array([[ 0.        , -1.        ,  0.        ,  0.83015565],
       [-1.        ,  0.        ,  0.        ,  0.02100808],
       [ 0.        ,  0.        ,  0.        , -1.        ],
       [ 0.83015565,  0.02100808, -1.        ,  0.        ]])

In [10]:
tester = friendship_decay(tester, party=[0,1,2])
tester

array([[ 0.        , -1.        ,  0.        ,  0.66412452],
       [-1.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        , -0.997     ],
       [ 0.66412452,  0.        , -0.997     ,  0.        ]])

In [11]:
tester = np.ones((4,4)) * 0.9
tester

array([[0.9, 0.9, 0.9, 0.9],
       [0.9, 0.9, 0.9, 0.9],
       [0.9, 0.9, 0.9, 0.9],
       [0.9, 0.9, 0.9, 0.9]])

In [12]:
tester = friendship_decay(tester, party=[1,2])
tester

array([[0.72, 0.72, 0.72, 0.72],
       [0.72, 0.72, 0.9 , 0.72],
       [0.72, 0.9 , 0.72, 0.72],
       [0.72, 0.72, 0.72, 0.72]])